### ISSUE TITLE
setupapi.dll doesn't link and the prebuilt dll doesn't work with the version Xgpro v12.88

### ISSUE THREAD

**Issue by Mrjagx** [radiomanV/TL866#64]
this is the error with the pre-built one:
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\USER32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library USER32.dll (which is needed by L"Z:\\home\\mrjag\\Downloads\\test\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library SETUPAPI.dll (which is needed by L"Z:\\home\\mrjag\\Downloads\\test\\Xgpro.exe") failed (error c000012f).
0024:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mrjag\\Downloads\\test\\Xgpro.exe" failed, status c0000135

linking errors while compiling:
/usr/bin/ld: cannot find -ladvapi32: No such file or directory
/usr/bin/ld: cannot find -luser32: No such file or directory
/usr/bin/ld: cannot find -lwinecrt0: No such file or directory
/usr/bin/ld: cannot find -lkernel32: No such file or directory
/usr/bin/ld: cannot find -lntdll: No such file or directory
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed
make: *** [Makefile:32: setupapi.dll] Error 2

system info:
OS: Pop!_OS 22.04 LTS x86_64
Kernel: Linux 6.12.10-76061203-generic

**Comment by radiomanV** [comment]
Hi, what wine version do you have? `wine --version`

**Comment by Mrjagx** [comment]
Hi here is the version installed:
$ wine --version
wine-6.0.3 (Ubuntu 6.0.3~repack-1)
PS: I've try it also with fedora 41, same issue.

**Comment by Mrjagx** [comment]
the version v12.45 works with an old dll i built myself back in 2023, the problem is that Xgpro SW checks the system clock or their server for updates and doesn't allow you to do anything with the programmer bugging you with dialog window to perform an update.
solution: i've created simple patch to bypass this check and for now I am working with this old version, but I am interested to know why the dll doesn't link.

**Comment by radiomanV** [comment]
Hi, i have updated my wine wrapper. I have downgraded the GLIBC version to work with linux distros which still use an old libc version. Also added some unimplemented functions which caused an early crash when dll is loaded.        

Regarding the wine 6.0.3 well, this is quite old, you should upgrade to a more recent version.  
Here is how to do this: https://gitlab.winehq.org/wine/wine/-/wikis/Debian-Ubuntu  

Since your Pop OS is an Ubuntu 22.04 you should install  wine like this: 
```
sudo dpkg --add-architecture i386
sudo mkdir -pm755 /etc/apt/keyrings
wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
sudo apt update
sudo apt remove --purge wine* && sudo apt autoremove
sudo apt install winehq-stable wine-stable-dev libtool automake
``` 
`libtool` and `automake` are used when you build with `./build_static.sh` provided script.   
If the provided dll does not work then please build the dll invoking the above script.  

>  but I am interested to know why the dll doesn't link   

Because you don't have the wine `dev` package installed (or the correct one)   

>  Xgpro SW checks the system clock or their server for updates and doesn't allow you to do anything with the programmer bugging you with dialog window to perform an update.   
 
Interesting, i never encounter this...  Can you post a capture with this nag window?

**Comment by Mrjagx** [comment]
Thank you for the above instruction, one question from my side which distro are you using ?

_

> Interesting, i never encounter this... Can you post a capture with this nag window?

_
here is the message dialog, if you click okay it will not perform any action (read, check write ... etc )
![Image](https://github.com/user-attachments/assets/73a72de9-81cd-4103-be46-84ac1b1a1a92)

**Comment by radiomanV** [comment]
Hi, i understand now. That message box will appear only when your firmware is newer than the version required by the software. I thought something else.   

For my personal machines i'm using only Ubuntu/Debian based distros. The dev. machine is running Kubuntu 24.10 right now, but i have Fedora at work. I'm also using  Debian without any DE installed used for SDR software and private ham radio streaming. I also use Linux Mint  with Mate DE in an  old notebook when working portable.   Sometimes i use Arch/Manjaro for testing purposes but is not my dayily OS.   

A quick test to see the `setupapi.dll`  required dependencies is to run `ldd -v ./setupapi.dll` command.   
If something is missing then it will appear as `not found` in the dependencies list.

**Comment by necroware** [comment]
Hello, unfortunately I seem to have a similar issues. I was not able to build the library on my own because of missing dependencies to 32-bit wine libraries which were dropped from archlinux main repo. Linking fails due to missing libraries. I didn't spend yet the time to build the dependencies from AUR, but tried the binary included in the repository. Unfortunately my T48 seems not to be detected. The Xgpro version is v12.90 and it runs in demo mode. I'll try to fall back to an older version for now.

**Comment by necroware** [comment]
The problem turned out to be a switch of Wine to exclusive WoW64 on ArchLinux since version 10.9. From now on this library doesn't work there anymore and it is also not possible to build it as is. So short term solution is to fall back to wine 10.8 package indeed. I guess, other distributions will follow soon, if not already, since everybody is trying to get rid of 32-bit native libraries. So long term solution would be probably to adapt this project if possible, however I'm not familiar with the abstraction layer and unfortunately can't tell what has to be done to make it right at this point.

**Comment by necroware** [comment]
Great work. Thank you very much. I briefly tested the software (on Arch) with T48 with Xgpro v12.96 (latest version so far) and the new broker/launcher worked out of the box. My T48 was detected properly, I could update the firmware and I could read an EPROM. I'll do more tests tomorrow and take a closer look at the code. I'm curious about the solution ;)

Thank you very much once again.
